# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cache:  https://pat-s.me/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
language: R
cache:
  - packages
  - $HOME/.ccache


before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf

addons:
  apt:
    packages:
      - ccache
      - libudunits2-dev
      - libgdal-dev


after_success:
  - Rscript -e 'covr::codecov()'
